### ISSUE TITLE
use (global) const for data that wont change

### ISSUE THREAD

**Issue by williballenthin** [osardar/sha256#5]
given that you clone H and K, they can be at least const, and maybe global?

https://github.com/osardar/sha256/blob/bceb018ac04ce82c03f4a2e1fec791579947bc4f/src/lib.rs#L30-L46

alternatively, any reason you don't return these values directly? why is the clone needed? avoiding allocations is another general goal i'd recommend.

**Comment by osardar** [comment]
I might have scrapped the clone thanks to `clippy`- but I did go through and pull out another `clone` 🎉. I was previously using them when I was not aware of the Copy trait handling (shallow?) data copies under the hood- thank you!
