### ISSUE TITLE
introduce alias types

### ISSUE THREAD

**Issue by williballenthin** [osardar/sha256#6]
consider introducing types to reflect the common data structures here, like H and K, maybe like:

```rs
type H = [u32; 8];
type K = [u32; 64];
```

and maybe a shortcut for your project local result type:

```rs
type Result<T> = std::error::Result<T, std::error::Error>
```

**Comment by osardar** [comment]
I like the idea of cutting down on some of that boilerplate code! Is it standard practice to override a std name, especially a common one like `Result`?
