### ISSUE TITLE
iterators instead of loops

### ISSUE THREAD

**Issue by williballenthin** [osardar/sha256#8]
you can try using iterators instead of some loops, which if nothing else, reduces the number of places you need to use `mut`:

https://github.com/osardar/sha256/blob/bceb018ac04ce82c03f4a2e1fec791579947bc4f/src/lib.rs#L161-L166

might be something like:

```rs
Ok(self.arr_h.iter().map(|h| h.to_be_bytes()).flatten().collect())
```

**Comment by osardar** [comment]
That's a clever way of getting around the need for a mut! That and flatten is awesome. Thanks!
